---
layout: cv
title: Emmanuel Ochieng's CV
---
# Emmanuel Ochieng
Student, Data Scientist, IT Specialist, System Administrator, and Database Programmer

<div id="webaddress">
<a href="https://linkedin.com/in/emmanueleraps" target="_blank">LikedIn</a>
| <a href="https://github.com/OchiengEmmanuel" target="_blank">My GitHub page</a>
</div>


## Currently

Standing on the shoulders of giants

### Specialized in

- Data Visaulization.
- Database Programming.
- System Administration
- Data Science
- IT Support



### Research interests

1. Optimizing data management systems: Researching scalable and resilient systems for handling growing data volumes.
2. Enhancing data security through AI-driven cybersecurity techniques and Integrating AI to improve database performance and management processes.
3. Exploring advanced data analytics
4. Exploring predictive modeling, machine learning, and data visualization for actionable insights.

## Education

<table>
  <tr>
    <td style="text-align:left; width: 20%;">Jan 2021 - now</td>
    <td style="text-align:left; width: 80%;"><strong>BSc in Applied Technology, Brigham Young University, Idaho</strong></td>
  </tr>
  <tr>
    <td style="text-align:left;">2020-2022</td>
    <td style="text-align:left;"><strong>Associate of Applied Science in Applied Technology, Brigham Young University, Idaho</strong></td>
  </tr>
  <tr>
    <td style="text-align:left;">2023</td>
    <td style="text-align:left;"><strong>Certificate in System Administration, Brigham Young University, Idaho</strong></td>
  </tr>
</table>

<!-- 
## Awards

`2012`
President, *Royal Society*, London, UK

Associate, *French Academy of Science*, Paris, France

-->

## Publications

- Comming soon

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) 

### Journals

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc.

### Patents

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001

-->

## Occupation

`2023 - 2024`
__Bloom/GMS__, Idaho

- Quality Assurance Specialist
- Mentor

`2021 - 2024`
__Airtel Kenya Network__, Kenya

- Manager
- Team Lead

`2017 - 2020`
__Ison BPO International__, Kenya

- Customer Support


<!-- ### Footer -->
<footer>
  <p>Last updated: December 2024</p>
</footer>